{{- if .Values.apiServicesManagement.installApiServices.enabled -}}
{{- if not .Values.templating.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "reports-server.fullname" . }}-pre-delete-api-services-cleanup
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "reports-server.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "100"
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 300
  template:
    metadata:
      {{- with .Values.jobConfigurations.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- with .Values.jobConfigurations.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- include "reports-server.labels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "reports-server.serviceAccountName" . }}
      {{- with .Values.jobConfigurations.podSecurityContext }}
      securityContext:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      {{- with .Values.jobConfigurations.imagePullSecrets | default .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      containers:
        - name: api-service-hook
          image: "{{ .Values.jobConfigurations.image.registry }}/{{ .Values.jobConfigurations.image.repository }}:{{ .Values.jobConfigurations.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jobConfigurations.image.pullPolicy | default "IfNotPresent" }}
          args:
            - uninstall
          {{- with .Values.jobConfigurations.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.jobConfigurations.tolerations | default .Values.tolerations}}
      tolerations:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- with .Values.jobConfigurations.nodeSelector | default .Values.nodeSelector }}
      nodeSelector:
        {{- tpl (toYaml .) $ | nindent 8 }}
      {{- end }}
      {{- if or .Values.jobConfigurations.podAntiAffinity .Values.jobConfigurations.podAffinity .Values.jobConfigurations.nodeAffinity }}
      affinity:
        {{- with .Values.jobConfigurations.podAntiAffinity }}
        podAntiAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.jobConfigurations.podAffinity }}
        podAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- with .Values.jobConfigurations.nodeAffinity }}
        nodeAffinity:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
      {{- end }}
{{- end -}}
{{- end -}}
