---
{{ if .Values.serviceAccountToken }}
apiVersion: v1
kind: Secret
metadata:
  name: nirmata-service-account-token
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  serviceAccountToken: {{ .Values.serviceAccountToken | b64enc }}
{{ end }}

