apiVersion: v2
name: cloud-controller
description: A Helm chart for Kubernetes
type: application
version: v0.4.1-rc2
appVersion: v0.4.1-rc6
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
