{{- if .Values.webhookEnabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kyverno-monitor
    app.kubernetes.io/instance: serving-cert
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: certificate
    app.kubernetes.io/part-of: kyverno-monitor
  name: kyverno-monitor-serving-cert
  namespace: {{ .Values.namespace }}
spec:
  dnsNames:
  - kyverno-monitor-webhook-service.kyverno-monitor-system.svc
  - kyverno-monitor-webhook-service.kyverno-monitor-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: kyverno-monitor-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kuberentes.io/name: issuer
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: kyverno-monitor
    app.kubernetes.io/instance: selfsigned-issuer
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: kyverno-monitor
  name: kyverno-monitor-selfsigned-issuer
  namespace: {{ .Values.namespace }}
spec:
  selfSigned: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: kyverno-monitor-system/kyverno-monitor-serving-cert
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: kyverno-monitor
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: kyverno-monitor
  name: kyverno-monitor-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: kyverno-monitor-webhook-service
      namespace: {{ .Values.namespace }}
      path: /validate-security-nirmata-io-v1-kyvernomonitor
  failurePolicy: Fail
  name: vkyvernomonitor.kb.io
  rules:
  - apiGroups:
    - security.nirmata.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - kyvernomonitors
  sideEffects: None
{{- end }}
