apiVersion: v2
name: nirmata-agent
description: A Helm chart for Nirmata Service Agents
type: application
version: 0.2.4-rc.3
appVersion: "v0.2.4-rc.3"
keywords:
  - kubernetes
  - serviceagents
  - argocd
  - remediation
maintainers:
  - name: "Nirmata"
    email: "support@nirmata.com"
dependencies:
  - name: crds
    version: 0.1.0
    condition: crds.install
