apiVersion: v1
name: venafi-adapter
version: v0.1.12
appVersion: v0.1.0
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Nirmata Venafi Adapter
keywords:
  - kubernetes
  - nirmata
  - venafi adapter
home: https://kyverno.io/
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
