{{- if .Values.kyverno.createCR }}
apiVersion: security.nirmata.io/v1alpha1
kind: Kyverno
metadata:
  annotations:
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
  name: kyverno
  namespace: {{ template "enterprise-kyverno.namespace" . }}
spec:
  secrets:
  
  namespace: {{ include "kyverno.namespace" . }}
  repository: {{ .Values.kyverno.image.repository }}
  version: {{ .Values.kyverno.image.tag }}
  replicas: {{ include "enterprise-kyverno.kyvernoReplicas" . }}

  helm:
    values:
      {{- if eq .Values.cloudPlatform "openshift" }}
      securityContext: null
      {{- end}}

      {{- if eq .Values.cloudPlatform "aks" }}
      webhookAnnotations:
        'admissions.enforcer/disabled': true
      {{- end}}

      {{- if eq .Values.cloudPlatform "eks" }}
      hostNetwork: true
      {{- end }}

      {{- toYaml .Values.kyverno.helm | nindent 6 }}
      cleanupController:
        image:
          repository: {{ trimSuffix "kyverno" .Values.kyverno.image.repository  }}cleanup-controller
          tag: {{ .Values.kyverno.image.tag }}
          pullSecrets:
          - name: image-pull-secret
      image:
        pullSecrets:
        - name: image-pull-secret
      initImage:
        repository: {{ trimSuffix "kyverno" .Values.kyverno.image.repository  }}kyvernopre
        tag: {{ .Values.kyverno.image.tag }}
      {{- if .Values.image.pullSecrets.create }}
      imagePullSecrets:
        'image-pull-secret':
          registry: {{.Values.image.pullSecrets.registry}}
          username: {{.Values.image.pullSecrets.username}}
          password: {{.Values.image.pullSecrets.password}}
      {{- end}}
      {{- if and (eq .Values.kyverno.enablePolicyExceptions true) (contains "v1.9" .Values.kyverno.image.tag) }}
      extraArgs:
      - --enablePolicyException=true
      - --loggingFormat=text
      - --exceptionNamespace={{ include "kyverno.namespace" . }}
      {{- end }}
      rbac:
        serviceAccount:
          name: kyverno
      licenseManager:
        imageRepository: {{ trimSuffix "kyverno" .Values.kyverno.image.repository  }}kyverno-license-manager
        imageTag: "v0.1.1"
        productName: ""
{{- end }}
