# Initialize oldVersion and NewVersion.
{{- $newVersion := trimPrefix "v" .Values.kyverno.image.tag }}
{{- $oldVersion := "" }}

{{- $namespace := include "enterprise-kyverno.namespace" . }}
{{- $lookupResult := (lookup "security.nirmata.io/v1alpha1" "Kyverno" $namespace "kyverno") }}
{{- if $lookupResult }}
  {{- $oldVersion = trimPrefix "v" (dig "spec" "version" "nothing" $lookupResult | toString )}}

  # Prevent skip upgrade.
  {{- $bkgMajor := 1 }}
  {{- $bkgMinor := 10 }}
  {{- $oldMajor := (split "." $oldVersion)._0 | int }}
  {{- $oldMinor := (split "." $oldVersion)._1 | int }}
  {{- $newMajor := (split "." $newVersion)._0 | int }}
  {{- $newMinor := (split "." $newVersion)._1 | int }}

  # Prevent upgrade from/to breaking version "1.10" and above
  {{ $cmpRes1 := atoi (include "verCmp" (dict "major1" $oldMajor "minor1" $oldMinor "major2" $bkgMajor "minor2" $bkgMinor)) }}
  {{ $cmpRes2 := atoi (include "verCmp" (dict "major1" $newMajor "minor1" $newMinor "major2" $bkgMajor "minor2" $bkgMinor)) }}
  {{- if or (and (gt $cmpRes1 -1) (lt $cmpRes2 0)) (and (gt $cmpRes2 -1) (lt $cmpRes1 0)) }}
    {{- fail (printf "upgrade from/to lower versions from/to v%d.%d, (%s->%s), is not allowed. Please contact Nirmata's Customer Success team for assistance at support@nirmata.com." $bkgMajor $bkgMinor $oldVersion $newVersion) }}
  {{- end }}
  
  # Skip upgrades also not allowed
  {{- if or (ne $oldMajor $newMajor) (gt $newMinor (add $oldMinor 1)) (gt $oldMinor (add $newMinor 1)) }}
    {{- fail (printf "skip upgrades (%s->%s) are not allowed" $oldVersion $newVersion) }}
  {{- end }}
{{- end }}

{{- if .Values.kyverno.createCR }}
apiVersion: security.nirmata.io/v1alpha1
kind: Kyverno
metadata:
  annotations:
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
  name: kyverno
  namespace: {{ template "enterprise-kyverno.namespace" . }}
spec:
  secrets:
  
  namespace: {{ include "kyverno.namespace" . }}
  repository: {{ .Values.kyverno.image.repository }}
  version: {{ .Values.kyverno.image.tag }}
  replicas: {{ include "enterprise-kyverno.kyvernoReplicas" . }}

  helm:
    values:
      {{- if eq .Values.cloudPlatform "openshift" }}
      securityContext: null
      {{- end}}

      {{- if eq .Values.cloudPlatform "aks" }}
      webhookAnnotations:
        'admissions.enforcer/disabled': 'true'
      {{- end}}

      {{- if eq .Values.cloudPlatform "eks" }}
      hostNetwork: true
      {{- end }}

      {{- toYaml .Values.kyverno.helm | nindent 6 }}
      cleanupController:
        image:
          tag: {{ .Values.kyverno.image.tag }}
      initImage:
        tag: {{ .Values.kyverno.image.tag }}
      {{- if and (eq .Values.kyverno.enablePolicyExceptions true) (contains "v1.9" .Values.kyverno.image.tag) }}
      extraArgs:
      - --enablePolicyException=true
      - --loggingFormat=text
      - --exceptionNamespace={{ include "kyverno.namespace" . }}
      {{- end }}
{{- end }}
