{{ $polstr := include "enterprise-kyverno.enabledPolicysets" . }}
{{ if and (contains "pod-security-restricted" $polstr) (not (contains "pod-security-baseline" $polstr)) }}
  {{ $polstr = printf "%s,%s" "pod-security-baseline" $polstr }}
{{ end }}

{{ $chartRepoUsername := .Values.policies.chartRepoUsername }}

{{ range $pol := $polstr | split "," }}

{{- $psetName := "invalid" -}}
{{- $psetType := "" -}}
{{- $chartRepo := "" -}}
{{- $chartName := "" -}}
{{- $version := "" -}}

{{- if eq $pol "k8s-best-practices" -}}
  {{- $psetName = "k8s-best-practices" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-policies" -}}
  {{- $chartName = "kubernetes-best-practice-policies" -}}
  {{- $version = "0.2.1" -}}
{{- else if eq $pol "pod-security-baseline" -}}
  {{- $psetName = "pod-security-baseline" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-policies" -}}
  {{- $chartName = "pss-baseline-policies" -}}
  {{- $version = "0.3.1" -}}
{{- else if eq $pol "pod-security-restricted" -}}
  {{- $psetName = "pod-security-restricted" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-policies" -}}
  {{- $chartName = "pss-restricted-policies" -}}
  {{- $version = "0.3.1" -}}
{{- else if eq $pol "rbac-best-practices" -}}
  {{- $psetName = "rbac-best-practices" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-policies" -}}
  {{- $chartName = "rbac-best-practice-policies" -}}
  {{- $version = "0.1.2" -}}
{{- else if eq $pol "multitenancy-best-practices" -}}
  {{- $psetName = "multitenancy-best-practices" -}}
  {{- $psetType = "helm" -}}
  {{- $chartRepo = "https://nirmata.github.io/kyverno-policies" -}}
  {{- $chartName = "multitenancy-best-practice-policies" -}}
  {{- $version = "0.1.2" -}}
{{- end -}}

{{- if ne $psetName "invalid" -}}
---
apiVersion: security.nirmata.io/v1alpha1
kind: PolicySet
metadata:
  annotations:
  labels:
    app.kubernetes.io/name: policyset
    app.kubernetes.io/instance: {{ $psetName }}
    app.kubernetes.io/part-of: enterprise-kyverno-operator
  name: {{ $psetName }}
  namespace: {{ template "enterprise-kyverno.namespace" $ }}
spec:
  {{ if eq $psetType "helm" }}
  source:
    helm:
      chartRepo: {{ $chartRepo }}
      chartName: {{ $chartName }}
      version: {{ $version }}
      username: {{ $chartRepoUsername}}
      passwordSecret: "{{ include "enterprise-kyverno.namespace" $ }}/operator-params/chartRepoPassword"
  {{ end }}

{{ end }}
{{ end }}
