{{- if .Values.image.pullSecrets.create }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "enterprise-kyverno.labels" $ | nindent 4 }}
    app: nirmata-kyverno-operator
  name: {{ default "image-pull-secret" .Values.image.pullSecrets.name }}
  {{- if .Values.globalAnnotations }}
  annotations: 
    {{- toYaml .Values.globalAnnotations| nindent 4 }}
  {{- end }}
  namespace: {{ include "enterprise-kyverno.namespace" . }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{ end }}
