{{- if .Values.rbac.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "enterprise-kyverno.fullname" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "enterprise-kyverno.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "enterprise-kyverno.fullname" . }}-installer
  namespace: {{ include "enterprise-kyverno.namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "enterprise-kyverno.fullname" . }}-installer
subjects:
- kind: ServiceAccount
  name: {{ template "enterprise-kyverno.rbac.serviceAccountName" . }}
  namespace: {{ template "enterprise-kyverno.namespace" . }}
{{- end }}
