apiVersion: v1
kind: Secret
metadata:
  name: operator-params
  labels:
    {{- include "enterprise-kyverno.labels" . | nindent 4 }}
    app: enterprise-kyverno
type: Opaque
data:
  licenseKey: {{ .Values.licenseKey | default "free-tier-license" | b64enc }}
  {{- if .Values.apiKey }}
  apiKey: {{ .Values.apiKey | b64enc }}
  {{- end }}
  
  {{- if .Values.policies.chartRepoPassword }}
  chartRepoPassword: {{ .Values.policies.chartRepoPassword | b64enc }}
  {{- end }}
