{{- if .Values.enableWebhook }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  {{- if eq .Values.certManager "cert-manager" }}
  annotations:
    cert-manager.io/inject-ca-from: {{ template "enterprise-kyverno.namespace" . }}/kyverno-operator-serving-cert
  {{- end}}
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/created-by: kyverno-operator
    app.kubernetes.io/instance: validating-webhook-configuration
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: validatingwebhookconfiguration
    app.kubernetes.io/part-of: kyverno-operator
  name: kyverno-operator-validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    {{- if eq .Values.certManager "other" }}
    caBundle: {{ .Values.caBundle }}
    {{- end}}
    service:
      name: {{ include "enterprise-kyverno.fullname" . }}
      namespace: {{ template "enterprise-kyverno.namespace" . }}
      path: /validate-security-nirmata-io-v1-kyvernooperator
  failurePolicy: Ignore
  name: vkyvernopolcpol.kb.io
  rules:
  - apiGroups:
    - kyverno.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - clusterpolicies
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1alpha1
  - v1beta1
  clientConfig:
    {{- if eq .Values.certManager "other" }}
    caBundle: {{ .Values.caBundle }}
    {{- end}}
    service:
      name: {{ include "enterprise-kyverno.fullname" . }}
      namespace: {{ template "enterprise-kyverno.namespace" . }}
      path: /validate-security-nirmata-io-v1alpha1-kyverno
  failurePolicy: Fail
  name: vkyverno.kb.io
  rules:
  - apiGroups:
    - security.nirmata.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - kyvernoes
  sideEffects: None
{{- end }}
