{{- if .Values.loki.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reports-server.fullname" . }}-loki-datasource
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "reports-server.labels" . | nindent 4 }}
    grafana_datasource: "1"
  annotations:
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        uid: loki
        access: proxy
        url: http://{{ .Release.Name }}-loki:3100
        isDefault: false
        editable: true
        jsonData:
          maxLines: 1000
          timeout: 60
{{- end }}
