{{- if .Values.config.disableAutoWebhookGeneration.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kyverno.fullname" . }}-disable-auto-webhook-generation
  namespace: {{ template "kyverno.namespace" . }}
  labels:
    {{- include "kyverno.labels.common" . | nindent 4 }}
data:
  webhooks: |
    {{- range .Values.config.disableAutoWebhookGeneration.webhooks }}
    - {{ . }}
    {{- end }}
{{- end }}
