apiVersion: v2
name: image-scan-adapter
description: A Helm chart for Kubernetes
type: application
version: "v0.1.1"
appVersion: "v0.1.0"
keywords:
  - kubernetes
  - nirmata
  - image
  - scan
  - adapter
  - policy
  - report
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
