apiVersion: v1
name: kyverno-operator
version: v0.1.9
appVersion: 0.1.0
icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
description: Kyverno Operator
keywords:
  - kubernetes
  - nirmata
  - kyverno operator
  - kyverno monitor
  - admissions controller
home: https://kyverno.io/
maintainers:
  - name: Nirmata
    url: https://nirmata.com/
kubeVersion: ">=1.20.0-0"
