{{- if and (eq .Values.awsAdapter.rbac.create true) (contains "v0.2" .Values.awsAdapter.image.tag) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kyverno-aws-adapter.namespace" . }}
{{- end}}