{{- if .Values.kyverno.admissionController.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno.admission-controller.roleName" . }}
  labels:
    {{- include "kyverno.admission-controller.labels" . | nindent 4 }}
{{- $commonAnnotations := include "kyverno.annotations.common" . | nindent 4 }}
{{- if $commonAnnotations }}
  annotations:
{{ $commonAnnotations }}
{{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kyverno.admission-controller.roleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kyverno.admission-controller.serviceAccountName" . }}
    namespace: {{ template "kyverno.namespace" . }}
{{- if .Values.kyverno.admissionController.rbac.createViewRoleBinding }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kyverno.admission-controller.roleName" . }}:view
  labels:
    {{- include "kyverno.admission-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.kyverno.admissionController.rbac.viewRoleName }}
subjects:
  - kind: ServiceAccount
    name: {{ template "kyverno.admission-controller.serviceAccountName" . }}
    namespace: {{ template "kyverno.namespace" . }}
{{- end -}}
{{- end -}}
