apiVersion: v2
name: nirmata-kyverno-operator
description: Helm Chart for Enterprise Kyverno Operator
type: application
version: v0.5.3-rc1
appVersion: v0.4.2-rc1

icon: https://github.com/kyverno/kyverno/raw/main/img/logo.png
keywords:
- kubernetes
- nirmata
- enterprise kyverno operator
- kyverno operator
home: https://kyverno.io/
maintainers:
- name: Nirmata
  url: https://nirmata.com/
kubeVersion: ">=1.20.0-0"
dependencies:
- name: crds
  version: 3.2.2
  condition: crds.install
