apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.10.0
  labels:
    app.kubernetes.io/part-of: enterprise-kyverno-operator
  creationTimestamp: null
  name: kyvernoadapters.security.nirmata.io
spec:
  group: security.nirmata.io
  names:
    kind: KyvernoAdapter
    listKind: KyvernoAdapterList
    plural: kyvernoadapters
    singular: kyvernoadapter
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.adapterType
      name: Adapter Type
      type: string
    - jsonPath: .spec.namespace
      name: Namespace
      type: string
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .status.isRunning
      name: Running
      type: boolean
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: KyvernoAdapter is the Schema for the kyvernoadapters API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: KyvernoAdapterSpec defines the desired state of KyvernoAdapter
            properties:
              adapterType:
                enum:
                - AWS
                - CIS
                - Venafi
                - Vulnerability
                type: string
              args:
                description: Args for adapter deployment
                items:
                  type: string
                type: array
              envVars:
                description: Environment variables for adapter deployment
                items:
                  type: string
                type: array
              helm:
                additionalProperties:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                description: Finer customizations for each component are provided
                  in a generic object structure, typically matching the value.yaml
                  of individual components
                type: object
              imagePullSecret:
                description: Adapter deployment image pull secret for private registries
                type: string
              namespace:
                type: string
              replicas:
                default: 1
                format: int32
                type: integer
              repository:
                description: Deployment image in repository
                type: string
              version:
                description: Image version tag
                type: string
            required:
            - adapterType
            - namespace
            - repository
            - version
            type: object
          status:
            description: KyvernoAdapterStatus defines the observed state of KyvernoAdapter
            properties:
              errorMsg:
                type: string
              isRunning:
                type: boolean
              lastUpdated:
                format: date-time
                type: string
            required:
            - isRunning
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
