apiVersion: v2
name: reports-server
type: application
version: 0.2.11
appVersion: v0.2.8
keywords:
- kubernetes
- policy reports storage
- postgresql
sources:
- https://github.com/nirmata/reports-server
maintainers:
- name: Nirmata
  url: https://nirmata.com/
  email: support@nirmata.com
kubeVersion: ">=1.16.0-0"
